

services:

  database:
    image: postgres:16.3-alpine

    restart: always

    env_file:
      - .env

  main_app:
    build:
      context: .

    ports:
      - 8000:8000

    depends_on:
      - database
    volumes:
      - .:/src

    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"

    env_file:
      - .env

